// Protocol type definitions

export interface SupplementaryItem {
  id: string;
  text: string;
  type: 'text' | 'file' | 'reference';
  context?: string; // Optional context for how this info should be used
  fileContent?: string; // For file attachments
  fileName?: string; // For file attachments
  ragChunks?: SupplementaryChunk[]; // Retrieved instead of sending entire files to AI
  structuredExtraction?: StructuredDocumentExtraction; // Tables/images extracted from uploaded documents
}

export interface SupplementaryChunk {
  id: string;
  text: string;
  sourceLabel: string;
  usage: string;
  type: 'text' | 'file' | 'reference';
  index: number;
}

export interface StructuredDocumentExtraction {
  extractionSummary?: string;
  warnings?: string[];
  tables?: Array<{
    id: string;
    title: string;
    source: string;
    confidence: 'high' | 'medium' | 'low';
    sourceFormat?: 'docx_table' | 'html_table' | 'text_table' | 'pdf_text_window' | 'ai_reconstructed';
    exactSourceAvailable?: boolean;
    preservationNote?: string;
    rawOoxml?: string;
    pageLayout?: {
      orientation: 'portrait' | 'landscape';
      widthTwips?: number;
      heightTwips?: number;
      margins?: {
        top?: number;
        right?: number;
        bottom?: number;
        left?: number;
        header?: number;
        footer?: number;
        gutter?: number;
      };
      source?: 'docx_section' | 'inferred';
    };
    headers: string[];
    rows: string[][];
    cells?: Array<Array<{
      text: string;
      colSpan?: number;
      rowSpan?: number;
      isHeader?: boolean;
    }>>;
    rawText: string;
    recommendedUse: 'schedule_of_activities' | 'study_schema' | 'general_reference';
  }>;
  images?: Array<{
    id: string;
    source: string;
    filename?: string;
    mediaType?: string;
    recommendedUse: 'study_schema' | 'general_reference';
    note: string;
    visionSummary?: string;
    imageDataUri?: string;
  }>;
}

export interface Protocol {
  id: string
  title: string
  lastEdited: Date
  phase?: string
  indication?: string
  status?: string
  createdBy?: string
  userId?: number
  createdAt?: Date
  synopsis?: string
  sourceExtraction?: StructuredDocumentExtraction
  protocolType?: string // Added protocol type property
  supplementaryInfo?: string[] | SupplementaryItem[] // Support both string array and structured items
  tableData: string | Record<string, { assessment: string; values: string[] }[]>
  tableHeaders: string | string[]
  soaProvenance?: {
    headerOrigins?: string[]
    removedItems?: any[]
    explanation?: string
    sourceStatus?: string
  }
  inclusionCriteria: string | Criterion[]
  exclusionCriteria: string | Criterion[]
  dataVariables: DataVariable[]
  studySchema?: string
  generatedProtocol?: string
  analyzedAt?: Date // Timestamp when AI analysis was completed
  components?: Array<{
    type?: string
    data?: any
    [key: string]: any
  }>
  sourceAssessment?: any
  overview?: { // Protocol overview generated by AI
    summary: string
    clinicalContext: string
    objectives: string
    endpoints: string
    design: string
    targetPopulation: string
    significance: string
    keyParameters?: Record<string, any>
  }
}

export interface Criterion {
  id: number
  text: string
  impact: string
  aiSuggestion: string
}

export interface DataVariable {
  id: number
  category: string
  name: string
  type: string
  required: boolean
  aiSuggestion: string
}

// API response types

export interface ProtocolListItem {
  id: string
  title: string
  phase: string
  indication: string
  status: string
  lastEdited: string
  createdBy: string
}

export interface CreateProtocolRequest {
  title: string
  phase: string
  indication: string
  synopsis: string
}

export interface GenerateWithAIRequest {
  synopsis: string
}

// Database entity types
export interface ProtocolEntity {
  id: string
  title: string
  phase: string
  indication: string
  status: string
  synopsis: string
  lastEdited: Date
  createdBy: string
  createdAt: Date
  tableData: string // JSON string
  tableHeaders: string // JSON string
  inclusionCriteria: string // JSON string
  exclusionCriteria: string // JSON string
  dataVariables: string // JSON string
}
